### ISSUE TITLE
Mixed content loading

### ISSUE THREAD

**Issue by z4nr34l** [spartanPAGE/scalajs-terminal#1]
Site is loading mixed content - font from google fonts „http://fonts.googleapis.com/css?family=Orbitron”

**Comment by spartanPAGE** [comment]
Fixed: https://github.com/spartanPAGE/scalajs-terminal/commit/8baf3685c263ea3e489df6b4b5987c842536a57b
![obraz](https://cloud.githubusercontent.com/assets/4762617/23021046/43fd32c4-f44a-11e6-8676-7b2e5f43aa29.png)
